In [1]:
import numpy as np

In [2]:
x = np.arange(20).reshape(2, 2, 5)

In [5]:
import torch

In [6]:
xt = torch.from_numpy(x)

In [7]:
xt.permute(1, 0, 2)

tensor([[[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14]],

        [[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19]]])

In [10]:
x1 = np.arange(60).reshape(5, 6, 2)

In [13]:
x2 = x1.reshape(5, 2, -1, 2)

In [17]:
x2

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]]],


       [[[48, 49],
         [50, 51],
         [52, 53]],

        [[54, 55],
         [56, 57],
         [58, 59]]]])

In [23]:
x1.transpose(2, 0, 1).reshape(-1, 2, 3, 1)

array([[[[ 0],
         [ 2],
         [ 4]],

        [[ 6],
         [ 8],
         [10]]],


       [[[12],
         [14],
         [16]],

        [[18],
         [20],
         [22]]],


       [[[24],
         [26],
         [28]],

        [[30],
         [32],
         [34]]],


       [[[36],
         [38],
         [40]],

        [[42],
         [44],
         [46]]],


       [[[48],
         [50],
         [52]],

        [[54],
         [56],
         [58]]],


       [[[ 1],
         [ 3],
         [ 5]],

        [[ 7],
         [ 9],
         [11]]],


       [[[13],
         [15],
         [17]],

        [[19],
         [21],
         [23]]],


       [[[25],
         [27],
         [29]],

        [[31],
         [33],
         [35]]],


       [[[37],
         [39],
         [41]],

        [[43],
         [45],
         [47]]],


       [[[49],
         [51],
         [53]],

        [[55],
         [57],
         [59]]]])

In [26]:
y = np.arange(15).reshape(5, 3)

In [27]:
np.tile(y, (2, 1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])